---

plugins:
  - jest

env:
  node: true
  jest: true
  es2020: true

parserOptions:
  ecmaVersion: 11 # Включает поддержку конструкции import.meta.url
  sourceType: module

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]